# Generated by Django 4.0.4 on 2022-05-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='lost',
        ),
        migrations.AddField(
            model_name='studentbadge',
            name='lost',
            field=models.BooleanField(default=False),
        ),
    ]
