# Generated by Django 4.0.4 on 2022-06-09 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentbadge',
            name='badge',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='students_badges', to='badges.badge'),
        ),
        migrations.AlterField(
            model_name='studentbadge',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='students_badges', to='badges.student'),
        ),
    ]
