# Generated by Django 4.0.4 on 2022-06-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mode',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mode',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
