# Generated by Django 4.0.4 on 2022-05-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mode',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
