# Generated by Django 4.0.4 on 2022-06-01 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_mode_amount_alter_mode_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default='2022-06-01 16:48:38'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(default='2022-06-01 17:48:38'),
        ),
        migrations.AlterField(
            model_name='mode',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='pages.event'),
        ),
    ]
