# Generated by Django 4.0.4 on 2022-05-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participant',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
