# Generated by Django 4.0.4 on 2022-06-02 10:48

from django.db import migrations, models
import django.utils.timezone
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_event_date_alter_event_end_alter_mode_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(default=pages.models.two_hours_hence),
        ),
    ]
