# Generated by Django 4.0.4 on 2022-05-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_mode_event_modes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Amount',
        ),
        migrations.AlterField(
            model_name='mode',
            name='type',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
