# Generated by Django 4.0.4 on 2022-05-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_participant_remove_event_participant_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
