# Generated by Django 4.0.4 on 2022-05-26 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_delete_amount_alter_mode_type_delete_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scan',
        ),
    ]
