<<<<<<< HEAD
# Generated by Django 4.0.4 on 2022-05-24 10:01
=======
# Generated by Django 4.0.4 on 2022-05-24 12:20
>>>>>>> 8ce54b259d19077bd9cf0a06647b73af453d20ff

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_delete_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='duration',
        ),
        migrations.AddField(
            model_name='event',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now),
<<<<<<< HEAD
            preserve_default=False,
=======
>>>>>>> 8ce54b259d19077bd9cf0a06647b73af453d20ff
        ),
    ]
