# Generated by Django 4.0.4 on 2022-05-25 14:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_event_date_alter_event_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='drinks',
        ),
        migrations.AddField(
            model_name='event',
            name='mode',
            field=models.ForeignKey(blank = True, null = True, on_delete=django.db.models.deletion.CASCADE, to='pages.mode'),
            preserve_default=False,
        ),
    ]
