# Generated by Django 4.0.4 on 2022-05-25 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_mode_remove_event_drinks_event_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='mode',
            field=models.OneToOneField(blank=True, null = True, on_delete=django.db.models.deletion.CASCADE, to='pages.mode'),
        ),
    ]
