# Generated by Django 4.0.4 on 2022-05-25 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_event_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mode',
            name='number',
        ),
        migrations.AlterField(
            model_name='event',
            name='mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.mode'),
            preserve_default=False,
        ),
    ]
