# Generated by Django 4.0.4 on 2022-05-25 14:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_remove_mode_number_alter_event_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='mode',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.mode'),
            preserve_default=False,
        ),
    ]
