# Generated by Django 4.0.4 on 2022-05-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_mode_amount_alter_event_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='mode',
        ),
        migrations.AddField(
            model_name='event',
            name='mode',
            field=models.ManyToManyField(to='pages.mode'),
        ),
        migrations.AlterField(
            model_name='mode',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
