# Generated by Django 4.0.4 on 2022-05-27 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_scan_mode'),
        ('api', '0002_scan_type'),
    ]

    operations = [
    ]
