# Generated by Django 4.0.4 on 2022-06-01 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_merge_0002_scan_mode_0002_scan_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='type',
        ),
    ]
