# Generated by Django 4.0.4 on 2022-06-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_scan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='login',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
