# Generated by Django 4.0.4 on 2022-06-09 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        ('api', '0005_scan_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.event'),
        ),
        migrations.AddField(
            model_name='scan',
            name='validity',
            field=models.BooleanField(default=False),
        ),
    ]
