# Generated by Django 4.0.4 on 2022-06-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mode',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mode',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
