# Generated by Django 4.0.4 on 2022-06-17 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_mode_amount_alter_mode_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scan',
        ),
    ]
